global:
  checkNewVersion: true
  sendAnonymousUsage: false

# API and Dashboard
api:
  dashboard: true # Enable the Traefik dashboard
  debug: false # Set to true for debugging
  insecure: false # IMPORTANT: Changed to false - use router for secure access

# Entry Points - Define ports and protocols
entryPoints:
  # HTTP Entry Point (Port 80)
  web:
    address: ":80"
    http:
      # Global HTTP -> HTTPS redirect
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
    # Trusted IPs for X-Forwarded headers
    forwardedHeaders:
      trustedIPs:
        - "172.20.0.0/24" # homelab network
        - "172.21.0.0/24" # media network
        - "127.0.0.1/32" # localhost
        - "10.0.0.0/8" # private network
        - "192.168.0.0/16" # private network

  # HTTPS Entry Point (Port 443)
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "leonardoacosta.dev"
            sans:
              - "*.leonardoacosta.dev"
      middlewares:
        - security-headers@file # Apply security headers globally
    forwardedHeaders:
      trustedIPs:
        - "172.20.0.0/24" # homelab network
        - "172.21.0.0/24" # media network
        - "127.0.0.1/32" # localhost
        - "10.0.0.0/8" # private network
        - "192.168.0.0/16" # private network

  # Traefik Dashboard Entry Point
  traefik:
    address: ":8080"

# Certificate Resolvers - Let's Encrypt Configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: "leo@leonardoacosta.dev" # Change to your email
      storage: "/letsencrypt/acme.json"
      keyType: EC256 # Use elliptic curve keys for better performance
      # Use HTTP-01 challenge (recommended for most homelab setups)
      httpChallenge:
        entryPoint: web
      # Uncomment for DNS challenge (if you use Cloudflare, Route53, etc.)
      # dnsChallenge:
      #   provider: cloudflare
      #   delayBeforeCheck: 30s
      #   resolvers:
      #     - "1.1.1.1:53"
      #     - "8.8.8.8:53"

# Ping - Healthcheck endpoint
ping:
  entryPoint: traefik

# Providers - Where Traefik gets its dynamic configuration
providers:
  # Docker provider - reads labels from Docker containers
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false # Only expose containers with traefik.enable=true
    network: homelab # Default network to use
    watch: true # Watch for Docker events in real-time
    # Automatically use the homelab network for containers on multiple networks
    useBindPortIP: false
    # Constraints to filter which containers Traefik should manage
    constraints: "Label(`traefik.enable`,`true`)"

  # File provider - for dynamic configuration files
  file:
    directory: "/dynamic"
    watch: true # Automatically reload on file changes

# Logging Configuration
log:
  level: "DEBUG" # DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  filePath: "/var/log/traefik/traefik.log"
  format: "common" # common or json
  # maxSize: 100      # Maximum size in MB before rotation
  # maxBackups: 10    # Number of old log files to keep
  # maxAge: 30        # Maximum number of days to keep old log files
  # compress: true    # Compress rotated files

# Access Logs - HTTP request logs
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: "common" # common or json
  bufferingSize: 100
  filters:
    statusCodes:
      - "400-599" # Only log errors (remove to log all requests)
    retryAttempts: true
    minDuration: "10ms"
  fields:
    defaultMode: keep
    headers:
      defaultMode: drop # Don't log headers by default (privacy)
      names:
        User-Agent: keep
        Referer: keep

# Metrics (Prometheus integration)
metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    entryPoint: traefik
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

# ServersTransport - Global transport configuration
serversTransport:
  insecureSkipVerify: true # Allow self-signed certificates for internal services
  maxIdleConnsPerHost: 200
  forwardingTimeouts:
    dialTimeout: "30s"
    responseHeaderTimeout: "30s"
    idleConnTimeout: "90s"

# # HTTP Configuration
# http:
#   # Encoding support
#   encoding:
#     gzip: true

# Experimental Features (Traefik v3)
experimental:
  # HTTP/3 support
  http3: true

# Host Resolver - For better local network resolution
hostResolver:
  cnameFlattening: true
  resolvConfig: "/etc/resolv.conf"
  resolvDepth: 5
