import { sqliteTable, integer, text, index } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
import { testFailures } from './failures';
import { openspecSpecs } from './openspec';

export const errorProposals = sqliteTable(
  'error_proposals',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    testFailureId: integer('test_failure_id')
      .notNull()
      .references(() => testFailures.id, { onDelete: 'cascade' }),
    specId: text('spec_id')
      .references(() => openspecSpecs.id, { onDelete: 'set null' }),
    generatedAt: integer('generated_at', { mode: 'timestamp' }).default(sql`(strftime('%s', 'now'))`).notNull(),
    lastFailureAt: integer('last_failure_at', { mode: 'timestamp' }).default(sql`(strftime('%s', 'now'))`).notNull(),
    autoGeneratedContent: text('auto_generated_content'), // JSON: { title, why, whatChanges, tasks }
    userModified: integer('user_modified', { mode: 'boolean' }).default(false).notNull(),
    occurrenceCount: integer('occurrence_count').default(1).notNull(),
  },
  (table) => ({
    testFailureIdx: index('idx_error_proposals_test_failure').on(table.testFailureId),
    specIdx: index('idx_error_proposals_spec').on(table.specId),
    generatedAtIdx: index('idx_error_proposals_generated_at').on(table.generatedAt),
  })
);

export type ErrorProposal = typeof errorProposals.$inferSelect;
export type NewErrorProposal = typeof errorProposals.$inferInsert;
