# Traefik v3 Dynamic Configuration - TLS Configuration
# This file defines TLS options and certificates

tls:
  # ============================================
  # TLS Options - Security configurations
  # ============================================
  options:
    # Modern TLS configuration (Recommended)
    modern:
      minVersion: "VersionTLS13"
      cipherSuites:
        - "TLS_AES_256_GCM_SHA384"
        - "TLS_AES_128_GCM_SHA256"
        - "TLS_CHACHA20_POLY1305_SHA256"
      curvePreferences:
        - "CurveP521"
        - "CurveP384"
      sniStrict: true
      alpnProtocols:
        - "h2"
        - "http/1.1"

    # Intermediate TLS configuration (Better compatibility)
    intermediate:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
        - "TLS_AES_256_GCM_SHA384"
        - "TLS_AES_128_GCM_SHA256"
        - "TLS_CHACHA20_POLY1305_SHA256"
      curvePreferences:
        - "CurveP384"
        - "CurveP256"
      sniStrict: false
      alpnProtocols:
        - "h2"
        - "http/1.1"

    # Default TLS configuration
    default:
      minVersion: "VersionTLS12"
      sniStrict: false
      alpnProtocols:
        - "h2"
        - "http/1.1"

  # ============================================
  # Custom Certificates (Optional)
  # ============================================
  # Uncomment if you have custom certificates
  # certificates:
  #   - certFile: "/certs/yourdomain.com.crt"
  #     keyFile: "/certs/yourdomain.com.key"
  #     stores:
  #       - default
  #   - certFile: "/certs/wildcard.yourdomain.com.crt"
  #     keyFile: "/certs/wildcard.yourdomain.com.key"
  #     stores:
  #       - default

  # ============================================
  # Certificate Stores
  # ============================================
  stores:
    default:
      defaultCertificate:
        # Let's Encrypt will provide this automatically
        # certFile: "/certs/default.crt"
        # keyFile: "/certs/default.key"
        {}
