services:
  # ? Traefik - Reverse Proxy
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Dashboard
    environment:
      - TZ=${TZ:-America/Chicago}
      - DOMAIN=${DOMAIN:-local}
      - TRAEFIK_DASHBOARD_USER=${TRAEFIK_DASHBOARD_USER}
      - TRAEFIK_DASHBOARD_PASSWORD=${TRAEFIK_DASHBOARD_PASSWORD}
    volumes:
      - ../traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ../traefik/dynamic:/dynamic:ro
      - ../traefik/letsencrypt:/letsencrypt
      - ../traefik/logs:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      homelab:
        ipv4_address: 172.20.0.81
      media:
        ipv4_address: 172.21.0.81
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=homelab"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAIN:-local}`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.middlewares=dashboard-auth@file"
      - "com.centurylinklabs.watchtower.enable=true"
      - "homepage.group=Infrastructure"
      - "homepage.name=Traefik"
      - "homepage.icon=traefik"
      - "homepage.href=https://traefik.${DOMAIN:-local}"
      - "homepage.description=Reverse Proxy & Load Balancer"

  # ? AdGuard Home - DNS Ad Blocker
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ../adguardhome/work:/opt/adguardhome/work
      - ../adguardhome/conf:/opt/adguardhome/conf
    ports:
      # Port 53 disabled - conflicts with systemd-resolved on runner
      - "53:53/tcp"
      - "53:53/udp"
      - "82:80/tcp" # Web interface (port 82 to avoid conflicts)
      - "8443:443/tcp" # HTTPS web interface
      - "3000:3000/tcp" # Initial setup
      - "853:853/tcp" # DNS-over-TLS
      - "784:784/udp" # DNS-over-QUIC
      - "853:853/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp" # DNSCrypt
      - "5443:5443/udp"
    networks:
      homelab:
        ipv4_address: 172.20.0.53
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
      - apparmor=docker-default
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=homelab"
      - "traefik.http.routers.adguardhome.rule=Host(`adguard.${DOMAIN:-local}`) || Host(`dns.${DOMAIN:-local}`)"
      - "traefik.http.routers.adguardhome.entrypoints=websecure"
      - "traefik.http.routers.adguardhome.tls=true"
      - "traefik.http.routers.adguardhome.tls.certresolver=letsencrypt"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=80"
      - "traefik.http.routers.adguardhome.middlewares=homelab-admin@file"

  # ? Home Assistant - Smart Home Hub
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    privileged: false
    environment:
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ../homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      # - /dev/ttyUSB0:/dev/ttyUSB0  # Uncomment for USB devices
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN # Only if needed for specific hardware
    ports:
      - "8123:8123"
    networks:
      homelab:
        ipv4_address: 172.20.0.123
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0  # Uncomment for USB devices
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8123 || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=homelab"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.${DOMAIN:-local}`) || Host(`ha.${DOMAIN:-local}`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls=true"
      - "traefik.http.routers.homeassistant.tls.certresolver=letsencrypt"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "traefik.http.routers.homeassistant.middlewares=homeassistant-headers@file"

  # ? Vaultwarden - Password Manager
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/Chicago}
      - DOMAIN=${VAULTWARDEN_DOMAIN:-https://vault.local}
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - SIGNUPS_ALLOWED=${VAULTWARDEN_SIGNUPS_ALLOWED:-false}
      - INVITATIONS_ALLOWED=${VAULTWARDEN_INVITATIONS_ALLOWED:-true}
      - WEBSOCKET_ENABLED=true
      - SENDS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
      - LOG_LEVEL=${VAULTWARDEN_LOG_LEVEL:-debug}
      - EXTENDED_LOGGING=true
      - SHOW_PASSWORD_HINT=false
      # DATABASE_URL not needed - defaults to /data/db.sqlite3
      - DATABASE_MAX_CONNS=10
      - IP_HEADER=X-Real-IP
      - ICON_CACHE_TTL=2592000
      - ICON_CACHE_NEGTTL=259200
    volumes:
      - ../vaultwarden/data:/data
    ports:
      - "8222:80"
      - "3012:3012"
    networks:
      homelab:
        ipv4_address: 172.20.0.22
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
