services:
  github-runner-1:
    image: myoung34/github-runner:latest
    container_name: github-runner-1
    restart: unless-stopped
    environment:
      - REPO_URL=${GITHUB_REPO_URL}
      - RUNNER_NAME=homelab-runner-1
      - RUNNER_TOKEN=${RUNNER_TOKEN_1}
      - RUNNER_WORKDIR=/tmp/runner-1-work
      - RUNNER_GROUP=Default
      - LABELS=self-hosted,Linux,X64,homelab,runner-1
      - EPHEMERAL=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-1-work:/tmp/runner-1-work
      - playwright-reports:/reports
    networks:
      - homelab
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    healthcheck:
      test: ["CMD", "pgrep", "-f", "Runner.Listener"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  github-runner-2:
    image: myoung34/github-runner:latest
    container_name: github-runner-2
    restart: unless-stopped
    environment:
      - REPO_URL=${GITHUB_REPO_URL}
      - RUNNER_NAME=homelab-runner-2
      - RUNNER_TOKEN=${RUNNER_TOKEN_2}
      - RUNNER_WORKDIR=/tmp/runner-2-work
      - RUNNER_GROUP=Default
      - LABELS=self-hosted,Linux,X64,homelab,runner-2
      - EPHEMERAL=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-2-work:/tmp/runner-2-work
      - playwright-reports:/reports
    networks:
      - homelab
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    healthcheck:
      test: ["CMD", "pgrep", "-f", "Runner.Listener"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  github-runner-3:
    image: myoung34/github-runner:latest
    container_name: github-runner-3
    restart: unless-stopped
    environment:
      - REPO_URL=${GITHUB_REPO_URL}
      - RUNNER_NAME=homelab-runner-3
      - RUNNER_TOKEN=${RUNNER_TOKEN_3}
      - RUNNER_WORKDIR=/tmp/runner-3-work
      - RUNNER_GROUP=Default
      - LABELS=self-hosted,Linux,X64,homelab,runner-3
      - EPHEMERAL=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-3-work:/tmp/runner-3-work
      - playwright-reports:/reports
    networks:
      - homelab
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    healthcheck:
      test: ["CMD", "pgrep", "-f", "Runner.Listener"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  github-runner-4:
    image: myoung34/github-runner:latest
    container_name: github-runner-4
    restart: unless-stopped
    environment:
      - REPO_URL=${GITHUB_REPO_URL}
      - RUNNER_NAME=homelab-runner-4
      - RUNNER_TOKEN=${RUNNER_TOKEN_4}
      - RUNNER_WORKDIR=/tmp/runner-4-work
      - RUNNER_GROUP=Default
      - LABELS=self-hosted,Linux,X64,homelab,runner-4
      - EPHEMERAL=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-4-work:/tmp/runner-4-work
      - playwright-reports:/reports
    networks:
      - homelab
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    healthcheck:
      test: ["CMD", "pgrep", "-f", "Runner.Listener"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  runner-1-work:
    driver: local
  runner-2-work:
    driver: local
  runner-3-work:
    driver: local
  runner-4-work:
    driver: local
  playwright-reports:
    external: true

networks:
  homelab:
    external: true
