# Storage Services
# Network attached storage, file sharing, and backup solutions

services:
  # ? Samba - Network Attached Storage
  samba:
    image: ghcr.io/servercontainers/samba:latest
    container_name: samba
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/Chicago}
      - USERID=${PUID:-1000}
      - GROUPID=${PGID:-1000}
      - SHARE1=${SAMBA_SHARE1:-Media;/media;yes;no;yes;all;none}
      - SHARE2=${SAMBA_SHARE2:-Backup;/backup;yes;no;no;all;none}
      - USER1=${SAMBA_USER:-user;SAMBA_PASSWORD}
      - SAMBA_USER=${SAMBA_USER}
      - SAMBA_PASSWORD=${SAMBA_PASSWORD}
      - RECYCLE=false
    volumes:
      - ${NAS_PATH:-/data}:/media
      # - ${BACKUP_PATH:-/backup}:/backup
    ports:
      - "445:445"
      - "139:139"
    networks:
      homelab:
        ipv4_address: 172.20.0.45
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
      - CAP_NET_ADMIN
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=false" # SMB doesn't work over HTTP
      - "com.centurylinklabs.watchtower.enable=true"
      - "homepage.group=Storage"
      - "homepage.name=Samba"
      - "homepage.icon=samba"
      - "homepage.href=smb://samba.${DOMAIN:-local}"
      - "homepage.description=Network File Share"

  # Additional storage services can be added here:
  # - Nextcloud
  # - Syncthing
  # - Minio
  # - Duplicati
  # - Restic
  # - etc.