# VPN and Security Services
# Network security and VPN connectivity

services:
  # ? Tailscale - Mesh VPN
  tailscale:
    image: docker.io/tailscale/tailscale:stable
    container_name: tailscale
    restart: unless-stopped
    hostname: homelab-tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ROUTES=${TS_ROUTES:-172.20.0.0/16,172.21.0.0/16}
      - TS_EXTRA_ARGS=--advertise-exit-node --accept-dns=false
    volumes:
      - ../tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host
    # sysctls must be set at host level with network_mode: host
    labels:
      - "traefik.enable=false" # Cannot use Traefik with host networking

  # ? Gluetun - VPN Client for Media Services
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      media:
        ipv4_address: 172.21.0.2
    ports:
      # Gluetun built-in services
      - "8888:8888/tcp" # HTTP proxy
      - "8388:8388/tcp" # Shadowsocks
      - "8388:8388/udp" # Shadowsocks
      # Services running through VPN
      - "9696:9696" # Prowlarr Web UI
      - "8090:8080" # qBittorrent Web UI (mapped to 8090 to avoid conflicts)
      - "6789:6789" # NZBGet Web UI
    volumes:
      - ../gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=${VPN_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=${VPN_ENDPOINT_PORT:-51820}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESS=${WIREGUARD_ADDRESS}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - FIREWALL_VPN_INPUT_PORTS=${FIREWALL_VPN_INPUT_PORTS}
      - FIREWALL_OUTBOUND_SUBNETS=172.21.0.0/16,172.20.0.0/16
      - HTTPPROXY=off
      - SHADOWSOCKS=off
      - DOT=off
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=off
      - BLOCK_ADS=off
      - UPDATER_PERIOD=24h
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
      - HTTP_CONTROL_SERVER_LOG=on
      - TZ=${TZ:-America/Chicago}
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
