# tap "homebrew/bundle"
# tap "homebrew/cask"
# tap "homebrew/core"
# Microsoft Azure CLI
brew "azure-cli"
# .NET runtime
brew "dotnet"
# Fast, highly customizable system info script, replaces neofetch
brew "hyfetch"
# Node.js
brew "node"
# nvm
brew "nvm"
# pnpm
brew "pnpm"
# starship
brew "starship"
# tmux - terminal multiplexer
brew "tmux"
# zsh-autosuggestions
brew "zsh-autosuggestions"
# zsh-syntax-highlighting
brew "zsh-syntax-highlighting"

# stripe
brew "stripe/stripe-cli/stripe"

# postgresql
brew "postgresql"

# Git Credential Manager - cross-platform Git credential storage
cask "git-credential-manager"

# Adobe Creative Cloud
# cask "adobe-creative-cloud"
# Beekeeper Studio
cask "beekeeper-studio"
# Bruno
cask "bruno"
# Cursor
cask "cursor"
# Discord
cask "discord"
# Fantastical
cask "fantastical"
# Font-Geist-Mono-Nerd-Font
cask "font-geist-mono-nerd-font"
# Gitkraken
cask "gitkraken"
# Google Chrome
cask "google-chrome"
# Notion
cask "notion"
# Obsidian
cask "obsidian"
# Raycast
cask "raycast"
# Spotify
cask "spotify"
# Steam
cask "steam"
# Superhuman
cask "superhuman"
# Telegram
# cask "telegram"
# Visual Studio Code
# cask "visual-studio-code"
# WezTerm
# cask "wezterm"
# Windows App
# cask "windows-app"