---
# Homer Configuration
# Homepage configuration
# See https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md

title: "Homelab Dashboard"
subtitle: "Your Personal Infrastructure Hub"
logo: "logo.png"
# icon: "fas fa-home" # Optional fontawesome icon

header: true
footer: '<p>Homelab Infrastructure | <a href="https://github.com/bastienwirtz/homer">Powered by Homer</a></p>'

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
# message:
#   url: https://b4bz.io
#   style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#   title: "Demo !"
#   icon: "fa fa-grin"
#   content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/yourusername/homelab"
    target: "_blank"
  - name: "Documentation"
    icon: "fas fa-book"
    url: "#"
  - name: "Wiki"
    icon: "fas fa-book-open"
    url: "#"

# Services
services:
  - name: "Infrastructure"
    icon: "fas fa-server"
    items:
      - name: "Nginx Proxy Manager"
        logo: "assets/tools/nginx-proxy-manager.png"
        subtitle: "Reverse Proxy & SSL Management"
        tag: "proxy"
        keywords: "reverse proxy nginx ssl"
        url: "http://172.20.0.81:81"
        target: "_blank"

      - name: "AdGuard Home"
        logo: "assets/tools/adguard-home.png"
        subtitle: "Network-wide Ad Blocking"
        tag: "dns"
        keywords: "adblock dns filtering"
        url: "http://172.20.0.53:82"
        target: "_blank"

      - name: "Tailscale Admin"
        logo: "assets/tools/tailscale.png"
        subtitle: "Mesh VPN Network"
        tag: "vpn"
        keywords: "vpn mesh network"
        url: "https://login.tailscale.com/admin"
        target: "_blank"

      - name: "Vaultwarden"
        logo: "assets/tools/vaultwarden.png"
        subtitle: "Password Manager"
        tag: "security"
        keywords: "passwords bitwarden vault"
        url: "http://172.20.0.22:8222"
        target: "_blank"

  - name: "Home Automation"
    icon: "fas fa-home"
    items:
      - name: "Home Assistant"
        logo: "assets/tools/home-assistant.png"
        subtitle: "Smart Home Hub"
        tag: "automation"
        keywords: "smart home automation"
        url: "http://172.20.0.123:8123"
        target: "_blank"

  - name: "AI & Development"
    icon: "fas fa-brain"
    items:
      - name: "Ollama WebUI"
        logo: "assets/tools/ollama.png"
        subtitle: "Local LLM Interface"
        tag: "ai"
        keywords: "llm ai ollama"
        url: "http://172.20.0.12:8081"
        target: "_blank"

      - name: "Ollama API"
        logo: "assets/tools/ollama.png"
        subtitle: "LLM API Endpoint"
        tag: "api"
        keywords: "llm api ollama"
        url: "http://172.20.0.11:11434"
        target: "_blank"

  - name: "Media & Entertainment"
    icon: "fas fa-play-circle"
    items:
      - name: "Jellyfin"
        logo: "assets/tools/jellyfin.png"
        subtitle: "Media Server"
        tag: "media"
        keywords: "media streaming movies tv"
        url: "http://172.20.0.96:8096"
        target: "_blank"

      - name: "Jellyseerr"
        logo: "assets/tools/jellyseerr.png"
        subtitle: "Media Request Management"
        tag: "requests"
        keywords: "media requests overseerr"
        url: "http://172.20.0.55:5055"
        target: "_blank"

      - name: "Radarr"
        logo: "assets/tools/radarr.png"
        subtitle: "Movie Collection Manager"
        tag: "movies"
        keywords: "movies automation download"
        url: "http://172.21.0.78:7878"
        target: "_blank"

      - name: "Sonarr"
        logo: "assets/tools/sonarr.png"
        subtitle: "TV Series Manager"
        tag: "tv"
        keywords: "tv series automation download"
        url: "http://172.21.0.89:8989"
        target: "_blank"

      - name: "Lidarr"
        logo: "assets/tools/lidarr.png"
        subtitle: "Music Collection Manager"
        tag: "music"
        keywords: "music automation download"
        url: "http://172.21.0.86:8686"
        target: "_blank"

      - name: "Bazarr"
        logo: "assets/tools/bazarr.png"
        subtitle: "Subtitle Manager"
        tag: "subtitles"
        keywords: "subtitles subs download"
        url: "http://172.21.0.67:6767"
        target: "_blank"

  - name: "Download Management"
    icon: "fas fa-download"
    items:
      - name: "qBittorrent"
        logo: "assets/tools/qbittorrent.png"
        subtitle: "Torrent Client (VPN)"
        tag: "torrent"
        keywords: "torrent download p2p"
        url: "http://172.21.0.2:8080"
        target: "_blank"

      - name: "Prowlarr"
        logo: "assets/tools/prowlarr.png"
        subtitle: "Indexer Manager (VPN)"
        tag: "indexers"
        keywords: "indexers trackers search"
        url: "http://172.21.0.2:9696"
        target: "_blank"

      - name: "NZBGet"
        logo: "assets/tools/nzbget.png"
        subtitle: "Usenet Client (VPN)"
        tag: "usenet"
        keywords: "usenet nzb download"
        url: "http://172.21.0.2:6789"
        target: "_blank"

  - name: "Storage & File Sharing"
    icon: "fas fa-hdd"
    items:
      - name: "Samba Share"
        logo: "assets/tools/samba.png"
        subtitle: "Network File Sharing"
        tag: "storage"
        keywords: "smb cifs file sharing nas"
        url: "smb://172.20.0.45"
        target: "_blank"

# Optional connectivity check
# This will check if the configured services are reachable and display a status indicator
connectivity:
  # You can use a custom API endpoint for status checks
  # url: "http://172.20.0.81/api/status"
  # OR use the default ping method (recommended for local services)
  method: "ping"

# Optional custom stylesheet
# stylesheet:
#   - "assets/custom.css"

# Optional custom javascript
# scripts:
#   - "assets/custom.js"