#!/usr/bin/env bash
# Homelab Bootstrap Script
# Runs on first boot via systemd service to deploy complete homelab stack

set -euo pipefail

# Configuration
LOG_FILE="/var/log/homelab-bootstrap.log"
USB_MOUNT="/run/media/$(whoami)/HOMELAB_USB"  # Adjust based on actual USB label
SECRETS_FILE="homelab-secrets.env.gpg"
REPO_URL="https://github.com/leonardoacosta/Installfest.git"
REPO_BRANCH="dev"
DEPLOY_PATH="$HOME/homelab"
TEMP_SECRETS="/tmp/homelab-secrets.env"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log() {
    echo -e "${BLUE}[$(date '+%Y-%m-%d %H:%M:%S')]${NC} $*" | tee -a "$LOG_FILE"
}

log_success() {
    echo -e "${GREEN}[$(date '+%Y-%m-%d %H:%M:%S')] ✓${NC} $*" | tee -a "$LOG_FILE"
}

log_error() {
    echo -e "${RED}[$(date '+%Y-%m-%d %H:%M:%S')] ✖${NC} $*" | tee -a "$LOG_FILE"
}

log_warning() {
    echo -e "${YELLOW}[$(date '+%Y-%m-%d %H:%M:%S')] ⚠${NC} $*" | tee -a "$LOG_FILE"
}

# Error handler
error_exit() {
    log_error "$1"
    log_error "Bootstrap failed! Check $LOG_FILE for details"
    exit 1
}

# Main execution
main() {
    log "=========================================="
    log "Homelab Bootstrap Starting"
    log "=========================================="

    # 1. Wait for USB to be mounted
    log "Step 1: Waiting for USB mount..."
    WAIT_COUNT=0
    while [ ! -d "$USB_MOUNT" ] && [ $WAIT_COUNT -lt 30 ]; do
        sleep 2
        WAIT_COUNT=$((WAIT_COUNT + 1))
    done

    if [ ! -d "$USB_MOUNT" ]; then
        error_exit "USB not found at $USB_MOUNT after 60 seconds"
    fi
    log_success "USB found at $USB_MOUNT"

    # 2. Decrypt secrets file
    log "Step 2: Decrypting secrets..."
    if [ ! -f "$USB_MOUNT/$SECRETS_FILE" ]; then
        error_exit "Secrets file not found: $USB_MOUNT/$SECRETS_FILE"
    fi

    # Prompt for GPG passphrase
    log "Please enter GPG passphrase to decrypt secrets:"
    if ! gpg --decrypt --output "$TEMP_SECRETS" "$USB_MOUNT/$SECRETS_FILE" 2>> "$LOG_FILE"; then
        error_exit "Failed to decrypt secrets file"
    fi
    log_success "Secrets decrypted"

    # 3. Source environment variables
    log "Step 3: Loading environment variables..."
    if [ ! -f "$TEMP_SECRETS" ]; then
        error_exit "Decrypted secrets file not found"
    fi

    # shellcheck disable=SC1090
    source "$TEMP_SECRETS"
    log_success "Environment variables loaded"

    # 4. Clone repository
    log "Step 4: Cloning Installfest repository..."
    if [ -d "$HOME/Installfest" ]; then
        log_warning "Repository already exists, pulling latest..."
        cd "$HOME/Installfest"
        git pull origin "$REPO_BRANCH" >> "$LOG_FILE" 2>&1 || log_warning "Git pull failed, continuing..."
    else
        if ! git clone -b "$REPO_BRANCH" "$REPO_URL" "$HOME/Installfest" >> "$LOG_FILE" 2>&1; then
            error_exit "Failed to clone repository"
        fi
    fi
    log_success "Repository ready"

    # 5. Generate unattended config file
    log "Step 5: Generating unattended configuration..."
    CONFIG_FILE="$HOME/Installfest/homelab/.homelab-config.yml"

    cat > "$CONFIG_FILE" << EOF
# Homelab Unattended Configuration
# Generated by homelab-bootstrap.sh on $(date)

unattended: true

# User configuration
user:
  name: ${USER}
  uid: $(id -u)
  gid: $(id -g)

# System configuration
system:
  timezone: ${TZ:-America/Chicago}
  domain: ${DOMAIN:-local}

# Service passwords
passwords:
  jellyfin: ${JELLYFIN_PASSWORD}
  vaultwarden: ${VAULTWARDEN_PASSWORD}
  adguard: ${ADGUARD_PASSWORD}
  samba: ${SAMBA_PASSWORD}
  traefik_dashboard: ${TRAEFIK_DASHBOARD_PASSWORD}

# VPN configuration
vpn:
  provider: ${VPN_PROVIDER}
  username: ${VPN_USERNAME}
  password: ${VPN_PASSWORD}

# Tailscale
tailscale:
  auth_key: ${TAILSCALE_AUTH_KEY}

# SMTP (Vaultwarden)
smtp:
  host: ${SMTP_HOST}
  port: ${SMTP_PORT:-587}
  username: ${SMTP_USERNAME}
  password: ${SMTP_PASSWORD}
  from: ${SMTP_FROM}

# GitHub Runner
github:
  runner_token: ${GITHUB_RUNNER_TOKEN}

# API Keys (will be generated if not set)
api_keys:
  radarr: ${RADARR_API_KEY:-}
  sonarr: ${SONARR_API_KEY:-}
  lidarr: ${LIDARR_API_KEY:-}
  prowlarr: ${PROWLARR_API_KEY:-}
  bazarr: ${BAZARR_API_KEY:-}
  jellyseerr: ${JELLYSEERR_API_KEY:-}
EOF

    log_success "Configuration file created"

    # 6. Securely delete decrypted secrets
    log "Step 6: Securely deleting decrypted secrets..."
    shred -vfz -n 3 "$TEMP_SECRETS" >> "$LOG_FILE" 2>&1 || {
        log_warning "shred not available, using rm"
        rm -f "$TEMP_SECRETS"
    }
    log_success "Secrets securely deleted"

    # 7. Execute homelab.sh in unattended mode
    log "Step 7: Executing homelab.sh..."
    cd "$HOME/Installfest/homelab"

    if [ ! -f "./homelab.sh" ]; then
        error_exit "homelab.sh not found in repository"
    fi

    chmod +x ./homelab.sh

    if ! ./homelab.sh --config "$CONFIG_FILE" >> "$LOG_FILE" 2>&1; then
        error_exit "homelab.sh execution failed"
    fi

    log_success "Homelab deployment completed!"

    # 8. Final status
    log "=========================================="
    log "Bootstrap completed successfully!"
    log "All services should now be running"
    log "Check service status: cd ~/Installfest/homelab && ./homelab.sh status"
    log "=========================================="

    # Disable this service so it doesn't run again
    log "Disabling bootstrap service..."
    sudo systemctl disable homelab-bootstrap.service || log_warning "Failed to disable service"

    log "Bootstrap script finished. Log available at: $LOG_FILE"
}

# Run main function
main "$@"
