name: Deploy Homelab (Streamlined)

on:
  push:
    branches: [main]
    paths:
      - "homelab/**"
      - ".github/workflows/deploy-homelab-streamlined.yml"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Homelab
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Services
        env:
          HOMELAB_PATH: ~/homelab
        run: bash homelab/scripts/deploy-ci-streamlined.sh

      - name: Check Deployment Status
        run: |
          cd ~/homelab
          docker compose ps

  validate:
    name: Validate Config
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: |
          cd homelab
          docker compose config -q